apiVersion: v1
kind: Pod
metadata:
  name: container-pod-1
  labels:
    app: primeiro-pod
spec:
  containers:
    - name: nginx
      image: nginx:latest
      ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: svc-pod-loadbalancer-1
spec:
  type: LoadBalancer
  ports:
    - port: 80
  selector:
    app: primeiro-pod
